### ISSUE TITLE
Plugin is not compatible with Geany 1.30.1

### ISSUE THREAD

**Issue by Ferrodata** [denizzzka/geany_dlang#2]
Current version does not work in Geany 1.30.1
When starting plugin manager an error occurs.

See console output for version:
`chris@celsius:~/.dub/packages/geany_dlang-0.0.1/geany_dlang$ dub build --build=release geany_dlang
Building package geany_dlang in /home/chris/.dub/packages/geany_dlang-0.0.1/geany_dlang/
Fetching geany_d_binding 0.0.2 (getting selected version)...
Performing "release" build using dmd for x86_64.
emsi_containers 0.5.3: target for configuration "library" is up to date.
libdparse 0.7.1: target for configuration "library" is up to date.
dsymbol 0.2.9: target for configuration "library" is up to date.
msgpack-d 1.0.0-beta.6: target for configuration "library" is up to date.
dcd 0.9.1: target for configuration "library" is up to date.
gtk-d:gtkd 3.6.6: target for configuration "library" is up to date.
geany_dlang 0.0.1: building configuration "default"...
Linking...
To force a rebuild of up-to-date targets, run again with --force.
`

**Comment by denizzzka** [comment]
Try to use Geany 1.31 version

**Comment by denizzzka** [comment]
Also, it should be build with GTK3 support.

**Comment by Ferrodata** [comment]
It works.
But to compile use the following steps:

>./autogen.sh --enable-gtk3
>make

NOT "./configure" before "make", this will go back to gtk2.x

**Comment by denizzzka** [comment]
README changed. Thanks!
